### ISSUE TITLE
paralogs_to_ref IndexError

### ISSUE THREAD

**Issue by emmawahl** [AntonelliLab/seqcap_processor#15]
Running paralogs_to_ref from latest version gives this error:

```
Processing sample AA9C
6 paralogous loci found.
Traceback (most recent call last):
  File "/home/emma/miniconda2/envs/secapr_env/bin/secapr", line 11, in <module>
    load_entry_point('secapr', 'console_scripts', 'secapr')()
  File "/home/emma/SECAPR/seqcap_processor-master/secapr/__main__.py", line 55, in main
    args.func(args)
  File "/home/emma/SECAPR/seqcap_processor-master/secapr/paralogs_to_ref.py", line 110, in main
    ref_seq = [ref for ref in ref_seqs if reference_id==ref.id][0]
IndexError: list index out of range

```
Previous steps carried out in SECAPR pipeline.

**Comment by tobiashofmann88** [comment]
Dear Emma,
I finally got to updating the pipeline and just released a new version to GitHub with a bugfix for that problem. However, it's not yet avilable on conda. To use the newest development version follow these steps:

**Comment by tobiashofmann88** [comment]
- download GitHub version
