### ISSUE TITLE
IndexError in "reference_assembly"

### ISSUE THREAD

**Issue by kq1986** [AntonelliLab/seqcap_processor#28]
Hello Tobias,

I followed your tutorial with the latest version (2.2.6) but it always gave this error when running the reference_assembly: 

**secapr reference_assembly --reads pipeline_exercise/cleaned_trimmed_reads --reference_type alignment-consensus --reference pipeline_exercise/alignments/contig_alignments --output pipeline_exercise/mapped_reads --min_coverage 4

Creating consensus sequences from input alignments...
Done.

##################################################
Processing sample T_pella5
Traceback (most recent call last):
  File "/public/home/kq/miniconda3/envs/secapr/bin/secapr", line 8, in <module>
    sys.exit(main())
  File "/public/home/kq/miniconda3/envs/secapr/lib/python3.8/site-packages/secapr/__main__.py", line 55, in main
    args.func(args)
  File "/public/home/kq/miniconda3/envs/secapr/lib/python3.8/site-packages/secapr/reference_assembly.py", line 825, in main
    sorted_bam = mapping_bwa(subfolder_path,reference,sample_id,sample_output_folder,args)
  File "/public/home/kq/miniconda3/envs/secapr/lib/python3.8/site-packages/secapr/reference_assembly.py", line 271, in mapping_bwa
    final_sam_name = samfiles[0]
IndexError: list index out of range**

Could you please help me identify the problem?

Thank you.

Qi

**Comment by tandermann** [comment]
Dear Qi,

The error should be fixed now in the newest version (v2.2.8). Let me know if you continue to run into problems!
