### ISSUE TITLE
IndexError in "reference_assembly" (secapr v 2.2.8)

### ISSUE THREAD

**Issue by kroeve** [AntonelliLab/seqcap_processor#40]
Hey there!

I run into the same issue #28  as a previous user in the version before when using `reference_assembly`:

    ##################################################
    Processing sample 200_Vappodes_phalaenopsis_AG_P15P9C_Bulbophyllum
    Traceback (most recent call last):
      File "/scratch3/kro037/.conda/envs/secapr/bin/secapr", line 10, in <module>
        sys.exit(main())
      File "/scratch3/kro037/.conda/envs/secapr/lib/python3.8/site-packages/secapr/__main__.py", line 55, in main
        args.func(args)
      File "/scratch3/kro037/.conda/envs/secapr/lib/python3.8/site-packages/secapr/reference_assembly.py", line 826, in main
        sorted_bam = mapping_bwa(subfolder_path,reference,sample_id,sample_output_folder,args,log)
      File "/scratch3/kro037/.conda/envs/secapr/lib/python3.8/site-packages/secapr/reference_assembly.py", line 271, in 
    mapping_bwa
        final_sam_name = samfiles[0]
    IndexError: list index out of range

My command looks like this: `secapr reference_assembly --reads output/600_secapr_prepare/ --reference_type user-ref-lib --reference data/Bulbo_SCOs_angio353_reduced_target_file_22_B_newportii.fasta --output output/601_secapr_test/02`

I don't know if that's relevant, but the sample in the error message is the 200th in the order of all my read subdirectories, not the first one. But it's the only one where an output folder was created for.

I'm using secapr v 2.2.8 installed through bioconda. Please let me know if any more info is needed.
Any help appreciated!

Cheers,
Evelin

**Comment by kroeve** [comment]
Hey there,

the issue was on my side, after checking the script I found that my reads were missing the "_clean-READ1.fastq.gz" suffix.

Cheers,
Evelin
